In [ ]:
import numpy as np

In [3]:
y_val = np.random.random((100, 3))
print y_val


[[  9.15307129e-01   4.34083717e-01   3.05642812e-02]
 [  2.61745496e-01   7.94272525e-02   3.69297181e-01]
 [  1.13524741e-01   6.12703542e-01   7.20983314e-01]
 [  9.56941918e-01   6.97407670e-02   2.75297900e-01]
 [  1.56703084e-01   2.57803224e-01   2.52599128e-02]
 [  5.28308020e-01   1.00577104e-01   8.98508026e-01]
 [  6.23633675e-03   3.06477472e-01   6.24596818e-01]
 [  2.83785921e-01   5.37242718e-01   4.31215889e-01]
 [  3.57592043e-01   3.57504299e-01   6.98088744e-01]
 [  9.87990977e-01   9.40948972e-01   8.21267684e-01]
 [  1.08029283e-01   2.33943564e-02   2.74320770e-01]
 [  1.07645395e-01   5.26806901e-01   8.21130996e-02]
 [  8.74237833e-02   3.37609738e-01   4.19090934e-01]
 [  4.50105399e-02   1.52347176e-02   5.06246845e-01]
 [  8.06813933e-01   2.83911331e-01   5.15580853e-01]
 [  5.86986670e-01   6.02794595e-01   2.97854570e-01]
 [  1.40749842e-01   9.28367734e-01   3.69165984e-01]
 [  5.67730757e-01   6.04093329e-01   9.17390398e-01]
 [  1.01402112e-01   2.91271